name: CI

on:
    push:
    pull_request:

jobs:
    static-analysis:
        name: 'Static Analysis'
        runs-on: [self-hosted, ubuntu]
        strategy:
            matrix:
                php-version:
                    - '8.1'

        steps:
            - name: 'Checkout'
              uses: actions/checkout@v3

            - name: 'Install PHP'
              uses: shivammathur/setup-php@v2
              with:
                  coverage: 'none'
                  php-version: '${{ matrix.php-version }}'
                  extensions: apcu, amqp, redis, ast, xsl, gd
                  tools: cs2pr
              env:
                  COMPOSER_TOKEN: ${{ secrets.COMPOSER_GITHUB_TOKEN }}
                  runner: self-hosted

            - name: 'Get composer cache directory'
              id: composercache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: 'Cache dependencies'
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key:
                      ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies
                      }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys:
                      ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies
                      }}-composer-

            - name: 'Install composer dependencies'
              run: composer install -n --no-progress --no-scripts --prefer-dist

            - name: 'Check code standards'
              run: ./vendor/bin/ecs check

            - name: 'Psalm'
              run: ./vendor/bin/psalm
